name: iOS App Signing

on:
  repository_dispatch:
    types: [resign] 
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID to process'
        required: true
        type: string
      job_url:
        description: 'Job URL to process'
        required: true
        type: string
      secret_key:
        description: 'Secret key to decrypt'
        required: true
        type: string
      api_token:
        description: 'API token to authenticate'
        required: true
        type: string

jobs:
  sign:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      # Support both workflow_dispatch (manual) and repository_dispatch (API)
      # workflow_dispatch uses 'inputs.*', repository_dispatch uses 'github.event.client_payload.*'
      SECRET_URL: "${{ inputs.job_url || github.event.client_payload.job_url }}"
      API_TOKEN: "${{ inputs.api_token || github.event.client_payload.api_token || secrets.API_TOKEN }}"
      JOB_ID: "${{ inputs.job_id || github.event.client_payload.job_id }}"
      SECRET_KEY: "${{ inputs.secret_key || github.event.client_payload.secret_key }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Fastlane Session
        uses: actions/cache@v4
        with:
          path: ~/.fastlane
          key: session-${{ github.run_id }}
          restore-keys: |
            session

      - name: Sign IPA
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pycryptodome cryptography
          PYTHONUNBUFFERED=1 ./sign.py
